//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace $rootnamespace$
{
	using Stardust.Nucleus;			

	public partial class AppBlueprint
    {
		protected override void ConfigureIoc(IConfigurator configuration)
        {
            //Do not edit this, add your configuration to the AppBlueprint.cs file as this will not be updated by the nuGet package in future releases.
			LoadConfiguration(configuration);
        }

		partial void LoadConfiguration(IConfigurator configuration);
    }
}
